sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker build -t yums/gitlab-ce-pages .
  - docker run --name gitlab-ce-pages -d --restart=always --env 'PAGE_PRIVATE_TOKEN=private_token_of_peeking_account' --env 'GITLAB_URL=http://localhost/' --env 'PROJECT_ROOT=public' --volume /srv/gitlab-ce-pages/public:/home/pages/public/ -p 8000:80 yums/gitlab-ce-pages
  - docker ps -a
  - cd src
  - npm install

script:
  - docker exec gitlab-ce-pages /bin/sh -c "PROJECT_ROOT=public GITLAB_CE_PAGES_PUBLIC_DIR=public PAGE_PRIVATE_TOKEN=private_token npm test"
  - WEBHOOK_URL=http://localhost:8000 npm run system_test
